<template>
  <div>
    <!-- Preloader -->
    <div v-if="loading" class="">
      <div
        class="
          preloader
          bg-dark
          flex-column
          justify-content-center
          align-items-center
        "
      >
        <svg
          id="loader-logo"
          xmlns="http://www.w3.org/2000/svg"
          xmlns:xlink="http://www.w3.org/1999/xlink"
          style="
            margin: auto;
            background: none;
            display: block;
            shape-rendering: auto;
          "
          width="200px"
          height="200px"
          viewBox="0 0 100 100"
          preserveAspectRatio="xMidYMid"
        >
          <path
            fill="none"
            stroke="#ffffff"
            stroke-width="8"
            stroke-dasharray="42.76482137044271 42.76482137044271"
            d="M24.3 30C11.4 30 5 43.3 5 50s6.4 20 19.3 20c19.3 0 32.1-40 51.4-40 C88.6 30 95 43.3 95 50s-6.4 20-19.3 20C56.4 70 43.6 30 24.3 30z"
            stroke-linecap="round"
            style="
              transform: scale(0.7100000000000001);
              transform-origin: 50px 50px;
            "
          >
            <animate
              attributeName="stroke-dashoffset"
              repeatCount="indefinite"
              dur="1.075268817204301s"
              keyTimes="0;1"
              values="0;256.58892822265625"
            ></animate>
          </path>
          <!-- [ldio] generated by https://loading.io/ -->
        </svg>
      </div>
    </div>

    <section class="section">
      <div class="fmxw-850 mx-auto">
        <!-- Spinner -->
        <div
          v-if="loading"
          class="h-100vh d-flex justify-content-center align-items-center"
        >
          <div
            class="spinner-border"
            style="width: 5rem; height: 5rem; position: relative; top: -95px"
            role="status"
          >
            <span class="sr-only">Loading...</span>
          </div>
        </div>
        <div v-else class="row justify-content-center mb-5 mb-lg-6">
          <div class="col-md-6">
            <div
              v-if="!imagesLoaded"
              class="h-100 d-flex justify-content-center align-items-center"
              style="height: 413px !important"
            >
              <div
                class="spinner-border"
                style="width: 3rem; height: 3rem"
                role="status"
              >
                <span class="sr-only">Loading...</span>
              </div>
            </div>

            <div
              v-else
              id="Carousel2"
              class="carousel slide mb-2"
              data-ride="carousel"
            >
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img
                    class="d-block w-100"
                    ref="image"
                    :src="images[0]"
                    alt="slide"
                  />
                </div>
                <div class="carousel-item">
                  <img class="d-block w-100" :src="images[1]" alt="slide" />
                </div>
                <div class="carousel-item">
                  <img class="d-block w-100" :src="images[2]" alt="slide" />
                </div>
                <div class="carousel-item">
                  <img class="d-block w-100" :src="images[3]" alt="slide" />
                </div>
                <div class="carousel-item">
                  <img class="d-block w-100" :src="images[4]" alt="slide" />
                </div>
                <div class="carousel-item">
                  <img class="d-block w-100" :src="images[5]" alt="slide" />
                </div>
              </div>
              <a
                class="carousel-control-prev"
                href="#Carousel2"
                role="button"
                data-bs-slide="prev"
              >
                <span
                  class="carousel-control-prev-icon"
                  aria-hidden="true"
                ></span>
                <span class="sr-only">Previous</span>
              </a>
              <a
                class="carousel-control-next"
                href="#Carousel2"
                role="button"
                data-bs-slide="next"
              >
                <span
                  class="carousel-control-next-icon"
                  aria-hidden="true"
                ></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
          </div>

          <div class="col-md-6 px-4">
            <div v-html="title" class="mb-2"></div>

            <div class="d-flex gap-1 align-items-center">
              <div
                class="Stars"
                :style="
                  '--rating: ' +
                  parsedScript.titleModule.feedbackRating.averageStar +
                  ';'
                "
              ></div>
              <p class="mb-0">
                <span class="fw-bold">{{
                  parsedScript.titleModule.feedbackRating.averageStar
                }}</span>
                -
                <span class="fw-bold"
                  >{{ parsedScript.titleModule.tradeCount }} Commandes</span
                >
              </p>
            </div>
            <hr class="my-4" />
            <div class="text-center">
              <!-- if no chosen price -->
              <div v-if="!chosenPrice">
                <p class="fw-bold fs-2 my-1" v-if="equalPrice > 0">
                  {{ new Intl.NumberFormat().format(Math.round(equalPrice)) }} <sup>DA</sup>
                  <span class="badge bg-danger">-{{ discount }}%</span>
                </p>
                <p v-else class="fw-bold fs-2 my-1">
                  {{ minPrice }} <sup>DA</sup> - {{ maxPrice }} <sup>DA</sup>
                </p>
              </div>
              <!-- if chosen price -->
              <div v-else class="d-flex justify-content-center align-items-center gap-2">
                <p class="fw-bold fs-2 my-1">{{ new Intl.NumberFormat().format(Math.round(chosenPrice)) }} <sup>DA</sup></p>
                <div v-if="discount">
                  <span class="fw-bold"><mark><del>{{new Intl.NumberFormat().format(Math.ceil((Math.round(chosenPrice)*100)/(100-discount)/10)*10)}}</del><sup>DA</sup></mark></span>
                  <span class="badge bg-danger">-{{ discount }}%</span>
                </div>
              </div>
              <div>
                <p v-if="shippingCost">
                  Shipping costs:
                  <span class="fw-bold">{{ new Intl.NumberFormat().format(Math.round(shippingCost)) }} <sup>DA</sup></span>
                </p>
                <p v-else>
                  Shipping costs: To be confirmed
                </p>
                <p v-if="shippingTime !== 'N/A'">
                  Livraison: {{ shippingTime }} jours
                </p>
                <p v-else>
                  Livraison: To be confirmed
                </p>
              </div>
            </div>
            <hr />
            <div v-for="option in options" :key="option.skuPropertyId">
              <fieldset class="mb-4">
                <legend class="h5" v-html="option.skuPropertyName"></legend>

                <div class="d-flex flex-wrap gap-2 flex-md-row flex-sm-fill">
                  <div
                    v-for="(item, index) in option.skuPropertyValues"
                    :key="index"
                    class="btn-group"
                    role="group"
                    aria-label="Basic radio toggle button group"
                  >
                    <input
                      type="radio"
                      class="btn-check"
                      :name="option.skuPropertyName"
                      :value="item.propertyValueDisplayName"
                      autocomplete="off"
                      :data-propId="item.propertyValueId"
                      :id="item.propertyValueDisplayName"
                      v-on:change="
                        setPropsId(
                          $event,
                          option.skuPropertyName,
                          options.length,
                          item.propertyValueDisplayName
                        )
                      "
                    />
                    <label
                      v-html="item.propertyValueDisplayName"
                      class="btn btn-outline-primary"
                      :for="item.propertyValueDisplayName"
                    ></label>
                  </div>
                </div>
                <!-- End of Radio -->
              </fieldset>
            </div>
            <div class="d-flex justify-content-center">
              <form @submit.prevent="addToCart">
                <button
                  class="btn btn-lg btn-primary fs-5 text-uppercase px-5 py-2"
                  type="submit"
                >
                  <div class="d-flex gap-2 align-items-center">
                    <span class="fas fa-cart-arrow-down d-inlineblock"></span>
                    <span>Ajouter</span>
                  </div>
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>

    <div
      style="
        position: fixed;
        top: calc(100vh - 100px);
        right: 2rem;
        z-index: 1055;
      "
    >
      <!-- <button id="show-modal" @click="showModal = true">Show Modal</button> -->
      <button
        id="showModal"
        style="box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1)"
        @click="showModal = true"
        target=""
        class="btn btn-tertiary position-relative"
      >
        <div style="">
          <i style="font-size: 2em" class="fas py-2 fa-shopping-cart me-2"></i>
          <span class="cart-number-2">
            {{ orderItems.length }}
          </span>
        </div>
      </button>
      <modal v-if="showModal" @close="showModal = false">
        <div slot="body">
          <div v-for="orderItem in orderItems" :key="orderItem.id">
            <p>
              <span class="fw-bold fs-5">Produit: </span>
              <span v-html="orderItem.title.substring(0, 100) + '...'"></span>
            </p>
            <p
              v-for="selectedProp in orderItem.selectedProps"
              :key="selectedProp.value"
            >
              <span
                class="fw-bold fs-5"
                v-html="selectedProp.name + ':'"
              ></span>
              <span v-html="selectedProp.selected" class="fw-bold fs-6"></span>
            </p>
            <p>
              <span class="fw-bold fs-5">Total: </span>
              <span class="fw-bold fs-6">{{ orderItem.totalSum }}DA</span>
            </p>
            <div class="d-block">
              <button
                class="btn btn-danger d-flex gap-1"
                @click="deleteOrderItem(orderItem.id)"
              >
                Supprimer
              </button>
            </div>
            <hr />
          </div>
        </div>
        <div slot="footer" class="d-flex">
          <button class="btn btn-success fs-6 text-white" @click="addOrder">
            Passez ma commande
          </button>
        </div>
      </modal>
    </div>
  </div>
</template>

<script>
export default {
  props: ["uri"],
  data() {
    return {
      showModal: false,
      loading: true,
      productId: null,
      title: "",
      images: [],
      options: [],
      script: null,
      parsedScript: null,
      imagesLoaded: false,
      selectedProps: [],
      obj: null,
      propsIdString: "",
      minPrice: 0,
      maxPrice: 0,
      equalPrice: 0,
      chosenPrice: null,
      fields: {},
      userId: this.$userId,
      orderItems: [],
      fee: 0,
      firstPrice: 0,
      usdP: null,
      shippingCost: 0,
      shippingTime: "N/A",
      discount: 0,
      oldPrice: 0,
    };
  },
  mounted() {
    this.loadInfo();
    this.fetchOrderItems();
  },
  created() {
    console.log("created");
    // this.loadInfo();
  },
  updated() {
    var image = new Image();
    image.src = this.images[0];
    image.onload = () => {
      this.imagesLoaded = true;
    };
  },
  methods: {
    loadInfo: function () {
      axios
        .get("/api/info", { params: { q: this.uri } })
        .then((response) => {
          console.log(response.data);
          this.images = response.data.images;
          this.script = response.data.script;
          this.shippingCost = Number(response.data.shippingCost) * 185;
          this.shippingCost = Math.ceil(this.shippingCost / 10) * 10;
          if (response.data.shippingTime) {
            this.shippingTime = response.data.shippingTime;
          }
          console.log("shipping cost", this.shippingCost);
          console.log("shipping time", this.shippingTime);
          // console.log(document.getElementsByClassName('carousel-item active')[0].childNodes[0].currentSrc);
        })
        .then(() => {
          var cleanedScript = this.getStringBetween(
            this.script,
            "data: ",
            ", csrfToken:"
          );
          this.parsedScript = JSON.parse(cleanedScript);
          // this.parsedScript = JSON.parse(this.script);
          // console.log(this.script)
          console.log(this.parsedScript);

          this.title = this.parsedScript.titleModule.subject;
          this.productId = this.parsedScript.commonModule.productId;
          console.log(this.productId);

          this.discount = this.parsedScript.priceModule.discount
          console.log('isDiscount', this.discount)

          // const options = JSON.parse(
          //   this.getStringBetween(
          //     this.script,
          //     'productSKUPropertyList":',
          //     ',"skuPriceList"'
          //   )
          // );
          // this.options = options;
          this.options = this.parsedScript.skuModule.productSKUPropertyList;
        })
        .then(() => {
          this.loading = false;
        })
        .then(() => {
          this.setMinMaxPrice();
        })
        .catch((err) => {
          console.log(err);
        });
    },
    getStringBetween: function (str, start, end) {
      const string = " " + str;
      let ini = string.indexOf(start);
      if (0 == ini) {
        return "";
      }
      ini += start.length;
      const len = string.indexOf(end, ini) - ini;
      return string.substr(ini, len);
    },
    setPropsId: function (e, propName, numberOfOptions, selectedPropertyName) {
      var propValue = e.target.getAttribute("data-propId");
      if (!this.selectedProps.length) {
        this.addProp(propName, propValue, selectedPropertyName);
      }

      var result = this.selectedProps.find((prop) => prop.name == propName);

      if (result) {
        result.value = propValue;
      } else {
        this.addProp(propName, propValue, selectedPropertyName);
      }
      console.log("selectedProps", this.selectedProps);
      this.setPropsIdString();
      this.setChosenPrice();
    },
    addProp: function (propName, value, selectedPropertyName) {
      this.obj = {
        name: propName,
        value: value,
        selected: selectedPropertyName,
      };
      this.selectedProps = [...this.selectedProps, this.obj];
      this.obj = null;
    },
    setPropsIdString: function () {
      this.selectedProps.forEach((prop, index) => {
        if (index == 0) {
          this.propsIdString = prop.value;
        } else {
          this.propsIdString += "," + prop.value;
        }
      });
      console.log("propsIdString", this.propsIdString);
    },
    setChosenPrice: function () {
      var selectedPack = this.parsedScript.skuModule.skuPriceList.filter(
        (item) => {
          return item.skuPropIds == this.propsIdString;
        }
      );
      if (selectedPack.length) {

        if(selectedPack[0].skuVal.actSkuCalPrice) {
          console.log(selectedPack)
          var price = selectedPack[0].skuVal.actSkuCalPrice * 185;
          price = Math.ceil(price / 100) * 100;
          var oldPrice = selectedPack[0].skuVal.skuCalPrice * 185;
          oldPrice = Math.ceil(oldPrice/10)*10
          this.oldPrice = oldPrice;
          console.log('oldPrice:', oldPrice)
          this.chosenPrice = price;
          //checking
          if (this.chosenPrice <= 2000) {
            this.fee = 400;
            this.fee = Math.ceil(this.fee / 100) * 100;
            console.log("fee: ", this.fee);
            this.firstPrice = this.chosenPrice;
            console.log("First Price: ", this.firstPrice);
            this.chosenPrice += this.fee;
          } else if (this.chosenPrice > 2000) {
            this.fee = this.chosenPrice * 0.08 + 400;
            this.fee = Math.ceil(this.fee / 100) * 100;
            console.log("fee: ", this.fee);
            this.firstPrice = this.chosenPrice;
            console.log("First Price:", this.firstPrice);
            this.chosenPrice += this.fee;
          }
          this.usdP = Number(selectedPack[0].skuVal.actSkuCalPrice);
          console.log("usdP", this.usdP);

        }else if(selectedPack[0].skuVal.skuCalPrice) {
            var price = selectedPack[0].skuVal.skuCalPrice * 185;
            price = Math.ceil(price / 100) * 100;
            this.chosenPrice = price;
            //checking
            if (this.chosenPrice <= 2000) {
              this.fee = 400;
              this.fee = Math.ceil(this.fee / 100) * 100;
              console.log("fee: ", this.fee);
              this.firstPrice = this.chosenPrice;
              console.log("First Price: ", this.firstPrice);
              this.chosenPrice += this.fee;
            } else if (this.chosenPrice > 2000) {
              this.fee = this.chosenPrice * 0.08 + 400;
              this.fee = Math.ceil(this.fee / 100) * 100;
              console.log("fee: ", this.fee);
              this.firstPrice = this.chosenPrice;
              console.log("First Price:", this.firstPrice);
              this.chosenPrice += this.fee;
            }
            this.usdP = Number(selectedPack[0].skuVal.skuCalPrice);
            console.log("usdP", this.usdP);
        }

      }
      console.log("chosen price", this.chosenPrice);
    },
    setMinMaxPrice: function () {
      this.parsedScript.skuModule.skuPriceList.forEach((item, index) => {
        console.log('item.skuVal.actSkuCalPrice: ', item.skuVal.actSkuCalPrice)
        // if no promotion
        if(!item.skuVal.actSkuCalPrice) {
          var price = Number(item.skuVal.skuCalPrice) * 185;
          console.log('price:', price);

          if (index == 0) {
          console.log('when index == 0');
          this.minPrice = price;
          console.log('minPrice:', this.minPrice);
          this.maxPrice = price;
          console.log('maxPrice:', this.maxPrice);
        } else {
          console.log('index is > 0');
          if (price < this.minPrice) {
            this.minPrice = price;
            console.log('minPrice:', this.minPrice);
            console.log('maxPrice:', this.maxPrice);
          } else if (price > this.maxPrice) {
            this.maxPrice = price;
            console.log('minPrice:', this.minPrice);
            console.log('maxPrice:', this.maxPrice);
          }
        }
        }else if(item.skuVal.actSkuCalPrice) {
        // if promotion
        var price = Number(item.skuVal.actSkuCalPrice) * 185;
        var oldPrice = Number(item.skuVal.skuCalPrice) * 185;
        var oldPrice = Math.ceil(oldPrice/100)*100;
        console.log('oldPrice:' , oldPrice);
        // price = Math.ceil(price/100)*100
        console.log('price:', price);
        if (index == 0) {
          console.log('when index == 0');
          this.minPrice = price;
          console.log('minPrice:', this.minPrice);
          this.maxPrice = price;
          console.log('maxPrice:', this.maxPrice);
        } else {
          console.log('index is > 0');
          if (price < this.minPrice) {
            this.minPrice = price;
            console.log('minPrice:', this.minPrice);
            console.log('maxPrice:', this.maxPrice);
          } else if (price > this.maxPrice) {
            this.maxPrice = price;
            console.log('minPrice:', this.minPrice);
            console.log('maxPrice:', this.maxPrice);
          }
        }
      }
      });

      if (this.minPrice == this.maxPrice) {
        this.equalPrice = this.minPrice;
        this.equalPrice = Math.ceil(this.minPrice / 100) * 100;
        //checking
        if (this.equalPrice <= 2000) {
            this.fee = 400;
            this.fee = Math.ceil(this.fee / 100) * 100;
            this.equalPrice += this.fee;
        } else if (this.equalPrice > 2000) {
            this.fee = this.equalPrice * 0.08 + 400;
            this.fee = Math.ceil(this.fee / 100) * 100;
            this.equalPrice += this.fee;
        }
        console.log('equalPrice', this.equalPrice);
      }

      //checking
      if (this.minPrice <= 2000) {
        this.minPrice = Math.ceil(this.maxPrice / 100) * 100;
        this.minPrice = this.minPrice + 400;
      } else if (this.minPrice > 2000) {
        this.minPrice += 400 + this.minPrice * 0.08; //400da + 8% of price
        this.minPrice = Math.ceil(this.minPrice / 100) * 100;
      }

      if (this.maxPrice <= 2000) {
        this.maxPrice = Math.ceil(this.maxPrice / 100) * 100;
        this.maxPrice = this.maxPrice + 400;
      } else if (this.maxPrice > 2000) {
        this.maxPrice += 400 + this.maxPrice * 0.08; //400da + 8% of price
        this.maxPrice = Math.ceil(this.maxPrice / 100) * 100;
      }
      this.minPrice += 100;
      this.maxPrice += 100;
      this.minPrice = new Intl.NumberFormat().format(Math.round(this.minPrice));
      this.maxPrice = new Intl.NumberFormat().format(Math.round(this.maxPrice));
    },
    addToCart: function () {
      axios
        .post(`api/addToCart/${this.userId}`, {
          title: this.title,
          totalSum: this.chosenPrice,
          selectedProps: JSON.stringify(this.selectedProps),
          user_id: this.$userId,
          uri: this.uri,
          productId: this.productId,
          usdP: this.usdP,
          fee: this.fee,
          shippingCost: this.shippingCost,
          shippingTime: this.shippingTime,
        })
        .then((response) => {
          this.fields = {}; //Clear input fields.
          console.log("added to cart");
          this.fetchOrderItems();
        })
        .catch((error) => {
          console.log(error);
        });
    },
    fetchOrderItems: function () {
      axios
        .get(`api/fetchOrderItems/${this.$userId}`)
        .then((response) => {
          console.log("fetch", response.data);
          this.orderItems = response.data;
        })
        .then(() => {
          this.setOrderItemsOptions();
        })
        .catch((error) => {
          console.log(error);
        });
    },
    setOrderItemsOptions: function () {
      this.orderItems.forEach((item) => {
        item.selectedProps = JSON.parse(item.selectedProps);
      });
    },
    deleteOrderItem: function (id) {
      axios
        .delete(`/api/deleteOrderItem/${id}`)
        .then((response) => {
          console.log(response.data);
          this.fetchOrderItems();
        })
        .catch((error) => {
          console.log(error);
        });
    },
    addOrder: function () {
      axios
        .post(`/api/addOrder/${this.$userId}`)
        .then((response) => {
          console.log("=====Order======", response.data);
          this.fetchOrderItems();
        })
        .catch((error) => {
          console.log(error);
        });
    },
  },
};
</script>

<style>
</style>